<a href="https://colab.research.google.com/github/AnaCristina1972/ProjetoOpenVC/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy 

In [ ]:
lista=[1,2,3,4,5]
x=numpy.array(lista)
print(x)

[1 2 3 4 5]


In [ ]:
x=numpy.array([1,2,3,4,5])
y=2
print(x+y)

[3 4 5 6 7]


In [ ]:
print(x-y)

[-1  0  1  2  3]


In [ ]:
print(y-x)

[ 1  0 -1 -2 -3]


In [ ]:
print(x*y)

[ 2  4  6  8 10]


In [ ]:
print(x/y)

[0.5 1.  1.5 2.  2.5]


In [ ]:
print(y/x)

[2.         1.         0.66666667 0.5        0.4       ]


In [ ]:
x=numpy.array([1,2,3,4,5])
y=numpy.array([6,7,8,9,10])
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(y+x)
print(y-x)
print(y/x)
print(y*x)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[ 7  9 11 13 15]
[5 5 5 5 5]
[6.         3.5        2.66666667 2.25       2.        ]
[ 6 14 24 36 50]


In [ ]:
z=numpy.sum(x)
print(z)

15


In [8]:
z=numpy.max(x)
print(z)
z=numpy.min(x)
print(z)

5
1


## Introdução ao Numpy


In [ ]:
x=numpy.random.randint(low=0,high=100,size=100)
print(x)

[39 14 16 46 41  5 95 63 63 40 31 70 98 81 89 76  1 28 78 78  6  0 32 56
  1 44 56 79 88 84 42 54 96 58 52 21 27 60 65 81 63  6 28 48 97 13 54 41
 55 29 98 77 30 34 70  7 91 13 68 81 89 78 56 93 72 23 73 71 78 99 37  6
 43 64 24 61  4 22 82 79 15 90 58 22 85 62 49 29 23 61  7 74 80 94 93 54
 47  6 57 60]


Media

In [ ]:
media=numpy.mean(x)
print(media)

52.77


Mediana

In [ ]:
mediana=numpy.median(x)
print(mediana)

56.0


Percentis

In [ ]:
percentil = numpy.percentile(x, 15)
print(percentil)

15.85


# Medidas de dispersão ou espalhamento


###intervalo ou amplitude

In [ ]:
valor_maximo = numpy.max(x)
valor_minimo = numpy.min(x)
intervalo = valor_maximo - valor_minimo
print(intervalo)

99


###Variância e desvio-padrão

In [ ]:
media = numpy.mean(x)
n = len(x)
diferencas = x - media
variancia = numpy.sum(diferencas * diferencas) / (n - 1)
desvio_padrao = numpy.sqrt(variancia)

print(variancia)
print(desvio_padrao)

835.6334343434344
28.90732492541353


###com ddof

In [ ]:
variancia = numpy.var(x, ddof=1)
desvio_padrao = numpy.std(x, ddof=1)
print(variancia)
print(desvio_padrao)

835.6334343434344
28.90732492541353
